language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3-numpy python3-matplotlib python3-pythonmagick
  - sudo apt-get install --qq python3-matplotlib python3-numpy
virtualenv:
  system_site_packages: true
install:
  - pip install .
script: nosetests
cache: apt
